// Code generated by mksysno_linux.py; DO NOT EDIT.

pub type Sysno = usize;

pub const SYS_O32_LINUX: Sysno = 4000;
pub const SYS_O32_LINUX_SYSCALLS: Sysno = 368;
pub const SYS_LINUX: Sysno = 5000;
pub const SYS_LINUX_SYSCALLS: Sysno = 328;
pub const SYS_64_LINUX: Sysno = 5000;
pub const SYS_64_LINUX_SYSCALLS: Sysno = 328;
pub const SYS_N32_LINUX: Sysno = 6000;
pub const SYS_N32_LINUX_SYSCALLS: Sysno = 332;
