#!/usr/bin/env python3
# Copyright (c) 2019 Xu Shaohua <xushaohua2016@outlook.com>. All rights reserved.
# Use of this source is governed by Apache License that can be found
# in the LICENSE file.

import re
import subprocess
import sys


def format_syscall(group):
    print("pub const E{0}: Errno = {1};".format(group[0].upper(), group[1]))


def main():
    cmd = ["gcc", "-E", "-dD", "/usr/include/errno.h"]
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE)
    out, err = p.communicate()
    if p.returncode != 0:
        sys.exit(1)

    if err:
        print(err)
        sys.exit(1)

    print("//\n// Code generated by mkerrno_linux.py; DO NOT EDIT.\n//\n")
    print("pub type Errno = i32;\n")

    errno_pattern = re.compile("^#define E(\w+)\s+(\d+)")
    for line in out.decode().split('\n'):
        m = errno_pattern.match(line)
        if m:
            format_syscall(m.groups())

    print("")


if __name__ == "__main__":
    main()

