#!/usr/bin/env python3
# Copyright (c) 2019 Xu Shaohua <xushaohua2016@outlook.com>. All rights reserved.
# Use of this source is governed by Apache License that can be found
# in the LICENSE file.

import re
import subprocess
import sys


def parse_syscall(header_file="/usr/include/asm/unistd.h"):
    cmd = ["gcc", "-E", "-dD", header_file]
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE)
    out, err = p.communicate()
    if p.returncode != 0:
        sys.exit(1)

    if err:
        print(err)
        sys.exit(1)

    lines = [
        "",
        "// Code generated by mksysno_linux.py; DO NOT EDIT.",
        "",
        "pub type Sysno = usize;",
        "",
    ]

    pattern = re.compile("^#define __NR_(\w+)\s+(\d+)")
    for line in out.decode().split("\n"):
        m = pattern.match(line)
        if m:
            line = "pub const SYS_{0}: Sysno = {1};".format(m.group(1).upper(), m.group(2))
            lines.append(line)
    return lines

def main():
    if len(sys.argv) == 2:
        lines = parse_syscall(sys.argv[1])
        line = "\n".join(lines)
        print(line)
    else:
        print("Usage: %s unistd.h" % sys.argv[0])
        sys.exit(1)

if __name__ == "__main__":
    main()

