#!/usr/bin/env python3
# Copyright (c) 2019 Xu Shaohua <xushaohua2016@outlook.com>. All rights reserved.
# Use of this source is governed by General Public License that can be found
# in the LICENSE file.

import re
import subprocess
import sys


def format_syscall(group):
    print("pub const SYS_{0} : usize = {1}".format(group[0].upper(), group[1]))


def main():
    cmd = ["gcc", "-E", "-dD", "/usr/include/syscall.h"]
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE)
    out, err = p.communicate()
    if p.returncode != 0:
        sys.exit(1)

    if err:
        print(err)
        sys.exit(1)

    print("//\n// Code generated by mksysnum_linux.py; DO NOT EDIT.\n//\n")

    for line in out.decode().split('\n'):
        m = re.match("^#define __NR_(\w+)\s+(\d+)", line)
        if m:
            format_syscall(m.groups())

    print("")


if __name__ == "__main__":
    main()
